name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - pip==18.1
    - python==3.6.13
    - numpy==1.19.5
    - matplotlib==2.1.0
    - jupyter
    - pillow==8.4.0
    - scikit-learn==0.20.1
    - scikit-image==0.15.0
    - scipy==1.1.0
    - h5py==2.10.0
    - eventlet==0.31.1
    - flask-socketio==4.3.1
    - seaborn==0.9.0
    - pandas==0.24.2
    - ffmpeg==4.2.2
    - imageio==2.1.2
    - pyqt=5.6.0
    - pip:
        - moviepy==0.2.3.2
        - opencv-python
        - requests==2.18.4
        - tensorflow==1.3.0
        - keras==2.1.2
